name: Publish
on:
  push:
  pull_request_target:
jobs:
  copy-go:
    runs-on: ubuntu-latest
    steps:
      - name: Copy generated Go
        uses: andstor/copycat-action@v3
        with:
          personal_token: ${{ secrets.APPARITOR_GITHUB_TOKEN }}
          src_path: /go/pb/.
          dst_path: /pb/.
          dst_owner: pomerium
          dst_repo_name: enterprise-client-go
          clean: true
  copy-python:
    runs-on: ubuntu-latest
    steps:
      - name: Copy generated Python
        uses: andstor/copycat-action@v3
        with:
          personal_token: ${{ secrets.APPARITOR_GITHUB_TOKEN }}
          src_path: /python/pb/.
          dst_path: /pb/.
          dst_owner: pomerium
          dst_repo_name: enterprise-client-python
          clean: true
